CREATE DATABASE IF NOT EXISTS sitedb;
USE sitedb;

CREATE TABLE IF NOT EXISTS CLIENTE(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(50),
    CARGO VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO(
     ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
     SENHA VARCHAR(255),
     FUNCIONARIO_ID INT,
     FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    CODIGO INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDA (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PAGAMENTO VARCHAR(20) NOT NULL, 
    PRODUTO_CODIGO INT,
    CLIENTE_ID INT, 
    FOREIGN KEY (PRODUTO_CODIGO) REFERENCES PRODUTO(CODIGO),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

/*
INSERT INTO FUNCIONARIO(NOME, CPF, EMAIL,CARGO,ENDERECO) 
VALUES ('Marcelo','03302276521','MarceloProfessor@hotmail.com','Professor/Editor','UTFPRTD');
INSERT INTO USUARIO(SENHA,FUNCIONARIO_ID) 
VALUES (MD5('2025'),LAST_INSERT_ID());

INSERT INTO PRODUTO(CODIGO, DESCRICAO, VALOR )
VALUES('47221','Política - Aristóteles', ' 50,99');
INSERT INTO PRODUTO(CODIGO, DESCRICAO, VALOR )
VALUES ('320340', 'Apologia a Sócrates - Platão', '30.99');
INSERT INTO PRODUTO (CODIGO, DESCRICAO, VALOR)
VALUES('332394', 'Retórica - Aristóteles', '20.50');
INSERT INTO PRODUTO (CODIGO,DESCRICAO,VALOR)
VALUES ('26524', 'Sobre a brevidade da vida - Sêneca', '43.89');
INSERT INTO PRODUTO (CODIGO, DESCRICAO, VALOR)
VALUES ('78865', 'O Príncipe - Maquiavel', '33.54');
INSERT INTO PRODUTO (CODIGO, DESCRICAO, VALOR)
VALUES ('04303', 'Metafísica - Aristóteles', '45.32');
*/ 

